---
- name: Install Microsoft Apt key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install VS Code apt repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install apps package (Ubuntu)
  package:
    name:
      - build-essential
      - git
      - python-pip
      - firefox
      - rpcbind
      - code
      - virtualenv
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install pip requirements inside virtualenv
  pip:
    name:
      - robotframework
      - robotframework-sshlibrary
      - robotframework-sikulilibrary
      - robotframework-seleniumlibrary
      - robotframework-ftplibrary
      - robotframework-snmplibrary
      - pyyaml
      - nclib
      - gecko
      - selenium
    virtualenv: "{{ user_directory.stdout }}/Developer/robot-env/"
    virtualenv_command: virtualenv
    virtualenv_site_packages: yes

- name: Verify if gecko driver already exists
  stat:
    path: "/tmp/geckodriver-v{{ gecko_version }}-linux64.tar.gz"
  register: hasGecko

- name: Verify if chrome driver already exists
  stat:
    path: "/tmp/chromedriver_linux64.zip"
  register: hasChrome

- name: Download the mozilla gecko driver
  get_url:
    url: "https://github.com/mozilla/geckodriver/releases/download/v{{ gecko_version }}/geckodriver-v{{ gecko_version }}-linux64.tar.gz"
    dest: /tmp
    mode: 0777
  when: not hasGecko.stat.exists

- name: Install the mozilla gecko driver
  unarchive:
    src: "/tmp/geckodriver-v{{ gecko_version }}-linux64.tar.gz"
    dest: /usr/local/bin/
    mode: 0755
    copy: no
    owner: root
    group: root

- name: Download the chrome driver
  get_url:
    url: "http://chromedriver.storage.googleapis.com/{{ chrome_version }}/chromedriver_linux64.zip"
    dest: /tmp
    mode: 0777
  when: not hasChrome.stat.exists

- name: Install the chrome driver
  unarchive:
    src: /tmp/chromedriver_linux64.zip
    dest: /usr/local/bin/
    mode: 0755
    copy: no
    owner: root
    group: root
