#!./wrapper/playbookwrapper.sh
---
- hosts: wsl
  become_method: sudo
  become_user: root
  vars_files:
    - vars/main.yml
  roles:
    - { role: sys-update, become: yes }
    - { role: sys-essentials, become: yes }
    - { role: user, become: yes }
    - { role: ohmyzsh, become: no }
    - { role: pyenv, become: no }
    - { role: poetry, become: no }
    - { role: nvm, become: no }
    - { role: docker, become: yes }
