---
- name: Add or modify user with ssh key
  user:
    name: "{{ loop_ohmyzsh_users.user_name }}"
    group: "{{ loop_ohmyzsh_users.user_name }}"
    generate_ssh_key: yes
    ssh_key_file: "{{ loop_ohmyzsh_users.user_home }}/.ssh/id_{{ ssh_key_type }}"
    ssh_key_type: "{{ ssh_key_type }}"
    ssh_key_comment: "{{ loop_ohmyzsh_users.user_email }}"
    shell: "{{ loop_ohmyzsh_users.user_shell }}"
