---
- name: Add apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18")

- name: Add apt-repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes
  become: yes
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18")

- name: Install docker on Ubuntu 18.04
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes
  notify: restart docker
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18")

- name: Install docker and docker-compose on Ubuntu 20.04
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
  become: yes
  notify: restart docker
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add current user to docker group
  user:
    name: "{{ loop_ohmyzsh_users.user_group }}"
    append: yes
    groups: docker
    system: yes
  become: yes
